image: Visual Studio 2017

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

build_script:
- ps: .\build.ps1 -BuildNumber "$env:APPVEYOR_BUILD_NUMBER" -RunTests $true

test: off

artifacts:
- path: .\.nupkgs\*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: eaiytjZ8451bGqdim49VhzfsYNDviMmEm/lMbc34oqmznMUEb0BW/9/yFckWyzf1
  on:
    branch: master
